apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "auth-node-app20"
  namespace: demo-prod
spec:
  destination:
    namespace: demo-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/intive-RedHat-Devex-demo/auth-node-app20
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
